### ISSUE TITLE
Quota limit leads to deletion of backup.php

### ISSUE THREAD

**Issue by Shoekrates** [eikowagenknecht/webhost_backup#1]
Hi Eiko,
every time the script reaches its' defined quota limit it starts deleting old files in the specified folder. That's perfect. Unfortunately it also deletes the backup.php and cron_backup.php which are also located in the backup folder according to your documentation. It seems the script checks only the creation date of all files and not if it is an actualbackup file? What can we do?
Regards, Christian

**Comment by eikowagenknecht** [comment]
Thanks for the hint, I'll have a look at it.

**Comment by eikowagenknecht** [comment]
In my blog post, I promoted a configuration as follows:

- The subdomain backup.phenx.de points to `(/www/htdocs/wxxxxxx)/phenx.de/backup`
- The scripts are located in `(/www/htdocs/wxxxxxx)/phenx.de/backup/backup`, this path is SSL protected
- The cron job runs `backup.phenx.de/backup/cron_backup.php`
- The directory where the actual backups are stored is `(/www/htdocs/wxxxxxx)/backups`

So the script should actually not be in the backup directory. This is a lot of "backup" folders so I see why it can be confusing and I'll add a workaround for your configuration and make sure only the actual backup files are deleted.

**Comment by eikowagenknecht** [comment]
Fixed in https://github.com/eikowagenknecht/webhost_backup/commit/8f2e3afa1e2c216f43f9399a04d7f8320dc83b18, now only the oldest .gz and .bz2 files will be deleted.
