### ISSUE TITLE
File ergänzt ...

### ISSUE THREAD

**Issue by cryd-s** [eikowagenknecht/webhost_backup#3]
Hallo, 
ich habe das Script installiert und entsprechend konfiguriert. Hat soweit gut funktioniert - Vielen Dank dafür!

Leider habe ich festgestellt wenn ich mehrmal am Tag ein Backup mache das er hier jeweils nur ein Archiv anlegt und dort entsprechend Dateien hinzufügt was bei mir zu Problemen führt.

Besteht die Möglichkeit hier jeweils eine File pro Backup zu erzeugen und nicht pro Tag?

**Comment by eikowagenknecht** [comment]
Ja das stimmt, das Szenario „mehrere Backups am Tag“ habe ich bisher nicht berücksichtigt. Ich schaue mal, was sich da machen lässt.

**Comment by cryd-s** [comment]
Das wäre super! Schreib gern hier falls du eine Lösung hast :) Vielleicht sogar mit ner kleinen Anleitung für PHP Dummies xD

**Comment by eikowagenknecht** [comment]
Ich habe nochmal drübergeschaut. Es sollte ausreichen, die Zeile
`$config["locale"]["filename_timestamp_format"] = "Y-m-d";`
durch
`$config["locale"]["filename_timestamp_format"] = "Y-m-d_H-i-s";`
zu ersetzen. Damit bekommen die Ergebnisdateinamen einen genaueren Timestamp, der nicht doppelt sein sollte. Magst du das mal ausprobieren?

**Comment by cryd-s** [comment]
Hi,

funktioniert perfek! Vielen lieben Dank!
